#! /bin/bash



if [[ $# -ne 2 ]]; then
    echo "rn *.extension *.new_extension" >&2
    exit 2
fi

old_suffix=$1
new_suffix=$2
for f in *.$old_suffix
do
    new_name=${f%.*}.$new_suffix
    echo Rename $f to $new_name
    mv ${f%.*}.$old_suffix $new_name
    RES=$?
    if [[ $RES -ne 0 ]]; then
	echo "Unable to find/rename file" >&2
	fi
    done


      
